### ISSUE TITLE
`resume export` errors with registryServer is not defined

### ISSUE THREAD

**Issue by lukemcgregor** [jsonresume/resume-cli#134]
Im just trying to get a resume exporting at all based on the docs on the site.

I created a JSON file containing the sample resume
I ran `resume export resume.pdf`

It outputs a bunch of errors and creates a 0 byte pdf.

I think the important error is this one:

 > node_modules\resume-cli\lib\export-resume\index.js:92
 >   .get(registryServer + '/pdf')
 >        ^
 > ReferenceError: registryServer is not defined

My Deets:

> **OS**: Windows
> **Node**: 0.12.4
> **resume-cli**: 0.4.2 (also tried 0.4.1)

Full trace is below:

> \Resume>resume export resume.pdf
> { [Error: ENOENT, no such file or directory '\Resume\.env']
>   errno: -4058,
>   code: 'ENOENT',
>   path: '\\Resume\\.env',
>   syscall: 'open' }
> 
>   running validation tests on resume.json ...
> 
>   √ Passed all validation tests.
> 
> To publish your resume at http://jsonresume.org type the command resume publish
> \npm\node_modules\resume-cli\lib\export-resume\index.js:92
>     .get(registryServer + '/pdf')
>          ^
> ReferenceError: registryServer is not defined
>     at sendExportPDFRequest (\npm\node_modules\resume-cli\lib\export-resume\index.js:92:10)
>     at \npm\node_modules\resume-cli\lib\export-resume\index.js:51:9
>     at Object.exports.extension (\npm\node_modules\resume-cli\lib\export-resume\menu.js:3:7)
>     at Object.exportResume (\npm\node_modules\resume-cli\lib\export-resume\index.js:45:10)
>     at Command.<anonymous> (\npm\node_modules\resume-cli\index.js:67:11)
>     at Command.listener (\npm\node_modules\resume-cli\node_modules\commander\index.js:301:8)
>     at Command.emit (events.js:110:17)
>     at Command.parseArgs (\npm\node_modules\resume-cli\node_modules\commander\index.js:610:12)
>     at Command.parse (\npm\node_modules\resume-cli\node_modules\commander\index.js:458:21)
>     at \npm\node_modules\resume-cli\index.js:86:11
>     at \npm\node_modules\resume-cli\node_modules\async\lib\async.js:46:16
>     at \npm\node_modules\resume-cli\node_modules\async\lib\async.js:532:17
>     at \npm\node_modules\resume-cli\node_modules\async\lib\async.js:526:17
>     at _arrayEach (\npm\node_modules\resume-cli\node_modules\async\lib\async.js:78:13)
>     at Immediate.taskComplete (\npm\node_modules\resume-cli\node_modules\async\lib\async.js:525:13)
>     at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by lukemcgregor** [comment]
Yeah that looks like the one, is there a working version I can use which doesn't have this issue?

**Comment by thomasdavis** [comment]
Oh looks like our PDF generation service is down again. Looking into it.

**Comment by shaun10** [comment]
Having problems with .html exports as well after update on OSX. Seems linked to registry server additions in latest commits.

**Comment by hearsid** [comment]
Getting the same error.
```
Siddharths-MacBook-Pro:myResume siddharthsharma$ resume export --format pdf siddharth.pdf

  running validation tests on resume.json ... 

Cannot export. There are errors in your resume.json schema format.

Unhandled rejection ReferenceError: sendExportPDFRequest is not defined
    at Object.exportResume (/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:36:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/index.js:69:11)
    at Command.listener (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:458:21)
    at /usr/local/lib/node_modules/resume-cli/index.js:88:11
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:570:21
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:167:37
    at /usr/local/lib/node_modules/resume-cli/lib/pre-flow/validate-schema.js:11:9
    at /usr/local/lib/node_modules/resume-cli/lib/test.js:60:13
    at /usr/local/lib/node_modules/resume-cli/node_modules/resume-schema/validator.js:16:9
    at tryCatcher (/usr/local/lib/node_modules/resume-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/resume-cli/node_modules/bluebird/js/release/promise.js:510:31)
```

**Comment by hearsid** [comment]
And the same error after fixing the json format issue.
```
Siddharths-MacBook-Pro:test siddharthsharma$ resume export --format pdf siddharth.pdf

  running validation tests on resume.json ... 

  ✓ Passed all validation tests. 

To publish your resume at http://jsonresume.org type the command resume publish
/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:36
      sendExportPDFRequest(resumeJson, fileName, theme, format, function() {
      ^

ReferenceError: sendExportPDFRequest is not defined
    at Object.exportResume (/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:36:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/index.js:69:11)
    at Command.listener (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:458:21)
    at /usr/local/lib/node_modules/resume-cli/index.js:88:11
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:550:17
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:544:17
    at _arrayEach (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:543:13)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```

**Comment by hearsid** [comment]
Have found the issue reopened here. 
https://github.com/jsonresume/resume-cli/issues/230
