### ISSUE TITLE
resume test and resume export validation failure

### ISSUE THREAD

**Issue by franzip** [jsonresume/resume-cli#160]
I tried to export my resume.json a couple of times and the CLI tool worked correctly, producing a plain PDF file with no theme used.

When I tried to use a different theme from the command line I started to get errors. 
To exclude a resume.json related problem I tried to use a blank resume.json file:

```
resume init
resume export --format pdf --theme slick
```

And I got errors.

Same with `resume export` without args.

`resume test` gave me the same exact errors.

The process ends creating an empty resume.pdf which produces an error on opening.

This is the full stack trace error:

`Unhandled rejection Error: Validation failed
    at Object.Report.toError (/usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:648:23)
    at Object.Report.toPromise (/usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:657:44)
    at finish (/usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1194:66)
    at ZSchema._validateSchema (/usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1225:20)
    at /usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1598:22
    at Object.Utils.forEach (/usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:195:34)
    at ZSchema.SchemaValidators.properties (/usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1596:19)
    at /usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1181:43
    at Object.Utils.forEach (/usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:195:34)
    at finish (/usr/local/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1176:19)
    at tryCatcher (/usr/local/lib/node_modules/resume-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/resume-cli/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/resume-cli/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/resume-cli/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/resume-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/resume-cli/node_modules/bluebird/js/main/async.js:133:10)`

**Comment by chrisdotcode** [comment]
When you say a blank resume.json file, do you literally mean a file with `{}` as its contents? I believe a blank object is indeed an invalid resume.json.

Can you replay this with a copy of the default resume.json created by `resume init`, and post any errors you get here?
