### ISSUE TITLE
Could not run the render function from local theme.

### ISSUE THREAD

**Issue by kneeki** [jsonresume/resume-cli#202]
I'm running into an issue while developing a theme whereas I'm unable to utilize the `resume serve` command to quick 'n easy theme development. The only error I'm given is pretty ambiguous with neither Google nor the freenode channel being helpful. I have the same results if I utilize a theme from any repo (like [Boilerplate](https://github.com/jsonresume/jsonresume-theme-boilerplate)) or if I specify my own resume.json. Running the command in a different directory (like ~/Downloads/) has the same result.

Running Ubuntu 15.10 on a MacBookAir.

Here's a copy/pasta of my terminal:

``` sh
dave@Dave-MacBookAir:/var/www/html/jsonresume-theme-Kate$ resume serve

Preview: http://localhost:4000
Press ctrl-c to stop

Could not find: /var/www/html/jsonresume-theme-Kate/resume.json
Using example resume.json from resume-schema instead...
Could not run the render function from local theme.
{ basics: 
   { name: 'Richard Hendriks',
     label: 'Programmer',
     picture: '',
     email: 'richard.hendriks@mail.com',
     phone: '(912) 555-4321',
     website: 'http://richardhendricks.com',
     summary: 'Richard hails from Tulsa. He has earned degrees from the University of Oklahoma and Stanford. (Go Sooners and Cardinals!) Before starting Pied Piper, he worked for Hooli as a part time software developer. While his work focuses on applied information theory, mostly optimizing lossless compression schema of both the length-limited and adaptive variants, his non-work interests range widely, everything from quantum computing to chaos theory. He could tell you about it, but THAT would NOT be a “length-limited” conversation!',
     location: 
      { address: '2712 Broadway St',
        postalCode: 'CA 94115',
        city: 'San Francisco',
        countryCode: 'US',
        region: 'California' },
     profiles: [ [Object], [Object] ] },
  work: 
   [ { company: 'Pied Piper',
       position: 'CEO/President',
       website: 'http://piedpiper.com',
       startDate: '2013-12-01',
       endDate: '2014-12-01',
       summary: 'Pied Piper is a multi-platform technology based on a proprietary universal compression algorithm that has consistently fielded high Weisman Scores™ that are not merely competitive, but approach the theoretical limit of lossless compression.',
       highlights: [Object] } ],
  volunteer: 
   [ { organization: 'CoderDojo',
       position: 'Teacher',
       website: 'http://coderdojo.com/',
       startDate: '2012-01-01',
       endDate: '2013-01-01',
       summary: 'Global movement of free coding clubs for young people.',
       highlights: [Object] } ],
  education: 
   [ { institution: 'University of Oklahoma',
       area: 'Information Technology',
       studyType: 'Bachelor',
       startDate: '2011-06-01',
       endDate: '2014-01-01',
       gpa: '4.0',
       courses: [Object] } ],
  awards: 
   [ { title: 'Digital Compression Pioneer Award',
       date: '2014-11-01',
       awarder: 'Techcrunch',
       summary: 'There is no spoon.' } ],
  publications: 
   [ { name: 'Video compression for 3d media',
       publisher: 'Hooli',
       releaseDate: '2014-10-01',
       website: 'http://en.wikipedia.org/wiki/Silicon_Valley_(TV_series)',
       summary: 'Innovative middle-out compression algorithm that changes the way we store data.' } ],
  skills: 
   [ { name: 'Web Development', level: 'Master', keywords: [Object] },
     { name: 'Compression', level: 'Master', keywords: [Object] } ],
  languages: [ { language: 'English', fluency: 'Native speaker' } ],
  interests: [ { name: 'Wildlife', keywords: [Object] } ],
  references: 
   [ { name: 'Erlich Bachman',
       reference: 'It is my pleasure to recommend Richard, his performance working as a consultant for Main St. Company proved that he will be a valuable addition to any company.' } ] } 'flat'
Requesting theme from server...
```

**Comment by mehtaphysical** [comment]
did you `npm install` before running `resume serve`?

**Comment by kneeki** [comment]
Very sorry for the delay with this response. `npm install` did fix the problem. Thank you!

**Comment by VaibhavP17** [comment]
Hi,
Even after npm install, it doesnt seem to be working. It seems to be giving error for over a month or so. Please help me out.

**Comment by aemonge** [comment]
same here

**Comment by javix64** [comment]
same here!

**Comment by thomasdavis** [comment]
@javix64 in the interim could you try https://github.com/rbardini/resumed 

are you linking the theme locally with npm? 

and/or how exactly are you attempting to develop a local theme? 

are you in a theme directory `cd jsonresume-theme-example` 

and then running `resume serve` ?

**Comment by thomasdavis** [comment]
@javix64 I've pushed up a new version should should fix your problem

try `resume serve --theme .` from within your local theme directory.

**Comment by javix64** [comment]
Hey @thomasdavis, first of all: thank you for dedicate your time to this project <3

First of all, I am using Node v21 without no issues in the common theme stackoverflow, I can run without problems any script.

I was trying to modify the archived theme: jsonresume-stackoverflow-react from @levino that is a fork from jsonresume-stackoverflow.

When I use ``resume serve --theme .``  in the jsonresume-stackoverflow, is working without any problem.

But the problem is when I try to use the same script in the stackoverflow-react theme.

This is the output of my console:
```
[javi@x535 jsonresume-theme-stackoverflow-react]$ npm run dev

> jsonresume-theme-stackoverflow-react@2.1.0 dev
> resume serve --theme .

{
  theme: '.',
  dir: 'public',
  resumeFilename: 'resume.json',
  cb: [Function (anonymous)]
}

Preview: http://localhost:4000
Press ctrl-c to stop

Error: Theme . could not be resolved relative to /home/javi/developing/jsonresume-theme-stackoverflow-react
    at _default (/home/javi/developing/jsonresume-theme-stackoverflow-react/node_modules/resume-cli/build/render-html.js:25:13)
    at /home/javi/developing/jsonresume-theme-stackoverflow-react/node_modules/resume-cli/build/builder.js:42:26
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
Could not run the render function from local theme.
...
--- my resume goes here ---
...
Requesting theme from server...
/home/javi/developing/jsonresume-theme-stackoverflow-react/node_modules/resume-cli/build/builder.js:9
  return value.match(/jsonresume-theme-(.*)/)[1];
                                             ^

TypeError: Cannot read properties of null (reading '1')
    at denormalizeTheme (/home/javi/developing/jsonresume-theme-stackoverflow-react/node_modules/resume-cli/build/builder.js:9:46)
    at sendExportHTML (/home/javi/developing/jsonresume-theme-stackoverflow-react/node_modules/resume-cli/build/builder.js:14:30)
    at /home/javi/developing/jsonresume-theme-stackoverflow-react/node_modules/resume-cli/build/builder.js:50:7

Node.js v21.6.2
```

**Comment by javix64** [comment]
Sorry Thomas. Something I did wrong. Now is running without any problem. 

Thank you!

**Comment by levino** [comment]
Hey @javix64, very happy to hear that you like my project.

Just FYI: I moved the source from [my repo](https://github.com/levino/jsonresume-theme-stackoverflow-react) to here. Also if you are changing the code because it lacks functionality that might be useful to others, let me know and I would happily review a PR.

**Comment by thomasdavis** [comment]
@DaveTacker "could not run the render function" is part of the theme-resolution family that generated the most reports here — it's being tracked against the revived codebase (see #784, kept open for exactly this).

Status update: **JSON Resume is under active maintenance again (2026)**, and resume-cli has been revived — development now happens in the [jsonresume.org monorepo](https://github.com/jsonresume/jsonresume.org) at [`packages/cli`](https://github.com/jsonresume/jsonresume.org/tree/master/packages/cli): Node 18+ support, the install-breaking husky hook removed, puppeteer bumped to `^23`, tests green. The npm package name `resume-cli` is unchanged. Full announcement: #786 · Consolidation tracking: [jsonresume/jsonresume.org#275](https://github.com/jsonresume/jsonresume.org/issues/275).

This standalone repo is being archived with a redirect, so I'm closing this out as part of the migration triage. If this still affects you on the revived version, please open a fresh issue in the monorepo where it will actually get eyes: https://github.com/jsonresume/jsonresume.org/issues. Thanks for taking the time to report it — and sorry it sat unanswered for so long.
