### ISSUE TITLE
Current master doesn't run

### ISSUE THREAD

**Issue by joshrivers** [jsonresume/resume-cli#226]
After this commit on master https://github.com/jsonresume/resume-cli/tree/75f0cf5536e0f130572985303cfa3018843cf89d resume-cli no longer runs for me, with the following error:

    Unhandled rejection TypeError: callback is not a function
        at /Users/josh/Code/joshrivers-resume-generation/node_modules/resume-cli/lib/pre-flow/validate-schema.js:11:9
        at /Users/josh/Code/joshrivers-resume-generation/node_modules/resume-cli/lib/test.js:60:13
        at /Users/josh/Code/joshrivers-resume-generation/node_modules/resume-schema/validator.js:16:9
        at tryCatcher (/Users/josh/Code/joshrivers-resume-generation/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/josh/Code/joshrivers-resume-generation/node_modules/bluebird/js/release/promise.js:510:31)
        at Promise._settlePromise (/Users/josh/Code/joshrivers-resume-generation/node_modules/bluebird/js/release/promise.js:567:18)
        at Promise._settlePromise0 (/Users/josh/Code/joshrivers-resume-generation/node_modules/bluebird/js/release/promise.js:612:10)
        at Promise._settlePromises (/Users/josh/Code/joshrivers-resume-generation/node_modules/bluebird/js/release/promise.js:687:18)
        at Async._drainQueue (/Users/josh/Code/joshrivers-resume-generation/node_modules/bluebird/js/release/async.js:138:16)
        at Async._drainQueues (/Users/josh/Code/joshrivers-resume-generation/node_modules/bluebird/js/release/async.js:148:10)
        at Immediate.Async.drainQueues (/Users/josh/Code/joshrivers-resume-generation/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:637:20)
        at tryOnImmediate (timers.js:610:5)
        at processImmediate [as _immediateCallback] (timers.js:582:5)

It appears that there is a breaking change with the Async library. This can probably be most easily fixed by merging in PR https://github.com/jsonresume/resume-cli/pull/222 where astephen2 noticed and reverted the updated version.

**Comment by thomasdavis** [comment]
Merged the PR and publishing an update.

**Comment by joshrivers** [comment]
Slight bug with the merge, but https://github.com/jsonresume/resume-cli/pull/231 fixes it.
