### ISSUE TITLE
Unexpected token on resume publish

### ISSUE THREAD

**Issue by bradydowling** [jsonresume/resume-cli#227]
With Node 4.6.1 on Ubuntu, I get the following error after running `resume publish`.

```
/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/resume-cli/lib/export-resume/index.js:16
  f(!theme.match('jsonresume-theme-.*')){
                                        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/resume-cli/lib/index.js:6:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/resume-cli/index.js:5:11)
    at Module._compile (module.js:409:26)
```

This is in a brand new Cloud9 IDE workspace. To reproduce, go to https://c9.io/new and select the Node environment. From there, just run `npm install -g resume-cli` then `resume publish`.

**Comment by thomasdavis** [comment]
Looking into it now

**Comment by thomasdavis** [comment]
Just bumped the version on NPM with a fix, let me know if it works.

**Comment by bradydowling** [comment]
Perfect, that did it 👍
