### ISSUE TITLE
Export continues to fail (sendExportRequest is not defined)

### ISSUE THREAD

**Issue by icarlosmendez** [jsonresume/resume-cli#230]
Is anyone else running into this issue? I have uninstalled and reinstalled 'globally' to no avail. 
Am I just missing something obvious? Output from command line below.

`MacBook-Pro:resume_json hive$ resume export resume.html --theme flat --format html

  running validation tests on resume.json ... 

  ✓ Passed all validation tests. 

To publish your resume at http://jsonresume.org type the command resume publish
/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:31
      sendExportRequest(resumeJson, fileName, theme, format, function() {
      ^
ReferenceError: sendExportRequest is not defined
    at Object.exportResume (/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:31:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/index.js:69:11)
    at Command.listener (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:458:21)
    at /usr/local/lib/node_modules/resume-cli/index.js:88:11
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:550:17
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:544:17
    at _arrayEach (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:543:13)
    at processImmediate [as _immediateCallback] (timers.js:367:17)`

**Comment by benhassara** [comment]
After a little investigating, it would appear that the problem is that the changes that were made by #222 to support local export were reverted by later commits. A checkout of `lib/export-resume/index.js` at a1c8725e6cb1116ab7bad831869da3e3d2c079c9 with the export menu changes from 3341e65b100baa154779b8dcd4ca7df0d52dfc71 should probably fix it. I'll submit a PR when I get a chance after work.

**Comment by fabricedekimpe** [comment]
@icarlosmendez 

I am experiencing the same problem.

➜  resume git:(master) ✗ resume export --theme elegant resume.html

  running validation tests on resume.json ...

  ✓ Passed all validation tests.

To publish your resume at http://jsonresume.org type the command resume publish
/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:31
      sendExportRequest(resumeJson, fileName, theme, format, function() {
      ^

ReferenceError: sendExportRequest is not defined
    at Object.exportResume (/usr/local/lib/node_modules/resume-cli/lib/export-resume/index.js:31:7)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/index.js:69:11)
    at Command.listener (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/resume-cli/node_modules/commander/index.js:458:21)
    at /usr/local/lib/node_modules/resume-cli/index.js:88:11
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:550:17
    at /usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:544:17
    at _arrayEach (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/usr/local/lib/node_modules/resume-cli/node_modules/async/lib/async.js:543:13)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by voncay** [comment]
+ 1
