### ISSUE TITLE
Error: Cannot find module 'jsonresume-theme-slick'

### ISSUE THREAD

**Issue by ryanburnett** [jsonresume/resume-cli#239]
I'm unable to export my json resume to html with the slick theme. Here's what I've tried:

```
cd jsonresume
npm install jsonresume-theme-slick
resume export index.html --format html --theme slick
running validation tests on resume.json ... 

  ✓ Passed all validation tests. 

To publish your resume at http://jsonresume.org type the command resume publish
module.js:327
    throw err;
    ^

Error: Cannot find module 'jsonresume-theme-slick'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at renderHtml (/Users/Ryan/.npm/lib/node_modules/resume-cli/lib/export-resume/index.js:66:18)
    at createHtml (/Users/Ryan/.npm/lib/node_modules/resume-cli/lib/export-resume/index.js:56:14)
    at Object.exportResume (/Users/Ryan/.npm/lib/node_modules/resume-cli/lib/export-resume/index.js:31:7)
    at Command.<anonymous> (/Users/Ryan/.npm/lib/node_modules/resume-cli/index.js:69:11)
    at Command.listener (/Users/Ryan/.npm/lib/node_modules/resume-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:87:13)
    at Command.emit (events.js:172:7)
    at Command.parseArgs (/Users/Ryan/.npm/lib/node_modules/resume-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/Ryan/.npm/lib/node_modules/resume-cli/node_modules/commander/index.js:458:21)
    at /Users/Ryan/.npm/lib/node_modules/resume-cli/index.js:88:11
    at /Users/Ryan/.npm/lib/node_modules/resume-cli/node_modules/async/lib/async.js:52:16
    at /Users/Ryan/.npm/lib/node_modules/resume-cli/node_modules/async/lib/async.js:550:17
```

My folder structure is:
```
/jsonresume/resume.json
/jsonresume/public/index.html
/jsonresume/node_modules/jsonresume-theme-slick
(and the slick theme's index.js, package.json, README.md, resume.template and style.css files)
```

I'm running:

* macOS 10.12.4 Beta
* npm 2.15.9

**Comment by thomasdavis** [comment]
With the recent change to not using the theme server, you have to install the theme locally. Not the best at the moment `npm install -g jsonresume-theme-slick`

**Comment by thomasdavis** [comment]
Added a warning message and hint for this error.
