### ISSUE TITLE
Kwan theme cannot be used

### ISSUE THREAD

**Issue by artspb** [jsonresume/resume-cli#243]
I've installed the Kwan theme and tried to use it. Here's the output.

```
> npm install -g jsonresume-theme-kwan
/usr/local/lib
└── jsonresume-theme-kwan@0.0.2 

> resume export --theme kwan resume.html

  running validation tests on resume.json ... 

  ✓ Passed all validation tests. 

To publish your resume at http://jsonresume.org type the command resume publish
You have to install this theme globally to use it e.g. `npm install -g jsonresume-theme-kwan`
```

The theme cannot be found although it was just installed. Export still works fine with other themes e.g. Stackoverflow.

**Comment by jonBoone** [comment]
noticed the same thing. after cloning the resume-cli repo and installing requirements (including jsonresume-theme-kwan) in the repo directory, it works within the directory...

**Comment by aodj** [comment]
I think this goes for any theme. I can't get the export to work with the `stackoverflow` theme despite the fact that `resume server --theme stackoverflow` works. I `npm install`-ed the [theme](https://github.com/francescoes/jsonresume-theme-stackoverflow) to no avail.

**Comment by Wenzel** [comment]
Hi,

i also have this issue.
I already installed the theme gloablly, multiple times, but `resume` is till complaining:

~~~
resume export resume.html --theme kendall

html-pdf: Failed to load PhantomJS module. { Error: Cannot find module 'phantomjs-prebuilt'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/html-pdf/lib/pdf.js:7:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/html-pdf/lib/index.js:1:73)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32) code: 'MODULE_NOT_FOUND' }

  running validation tests on resume.json ... 

  ✓ Passed all validation tests. 

To publish your resume at http://jsonresume.org type the command resume publish
You have to install this theme globally to use it e.g. `npm install -g jsonresume-theme-kendall`
~~~

~~~
$ sudo npm install -g jsonresume-theme-kendall
+ jsonresume-theme-kendall@0.1.18
added 52 packages in 2.426s
~~~

~~~
$ resume export resume.html --theme kendall
html-pdf: Failed to load PhantomJS module. { Error: Cannot find module 'phantomjs-prebuilt'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/html-pdf/lib/pdf.js:7:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/node_modules/html-pdf/lib/index.js:1:73)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32) code: 'MODULE_NOT_FOUND' }

  running validation tests on resume.json ... 

  ✓ Passed all validation tests. 

To publish your resume at http://jsonresume.org type the command resume publish
You have to install this theme globally to use it e.g. `npm install -g jsonresume-theme-kendall`
~~~

This is really **annoying** as we can only use the default theme now...

Can anyone look at this bug ?
Is there a temporary fix ? (manually installing the themes somewhere in `/usr/lib/node_something` ?)

Thanks.

**Comment by thomasdavis** [comment]
Maybe try installing phatomjs globally. (You shouldn't have to but would be good to know if it is the problem)

**Comment by Wenzel** [comment]
I already installed `phantomjs` using `apt-get` (package: [`phantomjs`](https://packages.ubuntu.com/xenial/phantomjs)).

So why is `resume` complaining about `phantomjs-prebuilt` ?

**Comment by Wenzel** [comment]
And when i try to install `phantomjs-prebuilt` using `npm`:

~~~
$ sudo npm install -g phantomjs-prebuilt
/usr/bin/phantomjs -> /usr/lib/node_modules/phantomjs-prebuilt/bin/phantomjs

> phantomjs-prebuilt@2.1.15 install /usr/lib/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/bin/phantomjs
Looks like an `npm install -g`
Could not link global install, skipping...
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1502804965963/phantomjs-2.1.1-linux-x86_64 -> /usr/lib/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1502804965963/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1502804965963/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/lib/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1502804965963/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tarrma/.npm/_logs/2017-08-15T13_49_28_860Z-debug.log
~~~

**Comment by chasebolt** [comment]
i ran into this same issue with the jsonresume-stackoverflow theme. the issue is resume is expecting the `devDepencies` from these themes to be installed. if you install all of the `devDepencies` at https://github.com/icoloma/jsonresume-theme-kwan/blob/master/package.json#L27-L34 by hand it will work.

**Comment by gaocegege** [comment]
Hi, I met the same issue, and I can not install the phantomjs-prebuilt globally, too.

Then I tried to run:

```bash
cd /usr/local/lib/node_modules/resume-cli
npm install phantomjs-prebuilt
```

Just install the phantomjs-prebuilt in the resume-cli, and it works well :)

**Comment by mrpintcom** [comment]
Edit this file in your local resume-cli npm installation.
https://github.com/jsonresume/resume-cli/blob/master/lib/export-resume/index.js

Right before this line (70):
>     console.log('You have to install this theme globally to use it e.g. `npm install -g ' + theme + '`')

Add this:
`console.log(err)`

Save the file and run the your export again. It will now show you the cause of the error instead of giving a default global install message.

My issue was a missing `underscore.string` package so I ran `npm install -g underscore.string` and everything worked after that.

**Comment by binarymist** [comment]
That works @mikhailrojo . Thanks.

**Comment by davidevernizzi** [comment]
@jphellemons, to make it work I had to install resume locally and run it locally:

```
# npm install resume-cli
# npm install jsonresume-theme-foobar
# node node_modules/resume-cli export --theme=foobar resume.html -r `pwd`/resume.json
```

pay attention to the `-r `pwd`/resume.json` because in my case it was not able to find the resume.json file.

I'm running on a Mac with OS 10.14, npm 6.9.0 and node v9.11.1.

Hope this helps

**Comment by lpillmann** [comment]
@davidevernizzi you are my hero. Worked like a charm after spending almost an hour in vain.
