### ISSUE TITLE
Can not register

### ISSUE THREAD

**Issue by babagugu** [jsonresume/resume-cli#267]
When running 
resume register

I am getting:
registering user
- registering...There has been an error publishing your resume
Your user session has been saved in the jsonresume.json config file in your home directory.

Versions used:
npm -v
5.5.1
resume -V
0.4.19

**Comment by babagugu** [comment]
At the first glance, this could be a mongoDB error on the server:

MongoError: server instance pool w
as destroyed
    at Function.MongoError.create (/root/registry-server/node_modules/mongodb-core/lib/error.js:29:11)
    at basicWriteV
alidations (/root/registry-server/node_modules/mongodb-core/lib/topologies/server.js:449:51)
    at Server.insert (/root/registry-server/node_modul
es/mongodb-core/lib/topologies/server.js:541:16)
    at Server.insert (/root/registry-server/node_modules/mongodb/lib/server.js:385:17)
