### ISSUE TITLE
Validation fails with valid resume when not connected to the internet

### ISSUE THREAD

**Issue by worp1900** [jsonresume/resume-cli#268]
resume test
fails with

    Unhandled rejection Error: Validation failed
        at Report.toError (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:648:23)
        at Report.toPromise (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:657:44)
        at finish (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1194:66)
        at ZSchema._validateSchema (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1225:20)
        at /Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1598:22
        at Object.forEach (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:195:34)
        at ZSchema.properties (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1596:19)
        at /Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1181:43
        at Object.forEach (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:195:34)
        at finish (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:1176:19)
        at tryCatcher (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/bluebird/js/release/promise.js:693:18)
        at Async._drainQueue (/Users/worp/.nvm/versions/node/v8.3.0/lib/node_modules/resume-cli/node_modules/bluebird/js/release/async.js:133:16)

on valid resumes when not connected to the internet.

Connecting to Wifi and running `resume test` again succeeds as expected.

`resume test` should, afaic, not need the internet at all. But if it has to, it should fail with a graceful message, informing that connectivity is needed.

A hint in the docs might also be helpful.

**Comment by worp1900** [comment]
@thomasdavis has this been resolved? Or why is it closed?
