### ISSUE TITLE
how to generate resume after installing resume-cli and theme e.g. stackoverflow2

### ISSUE THREAD

**Issue by ShantaramTupe** [jsonresume/resume-cli#270]
I have installed `resume-cli` and `theme` **e.g. stackoverflow2** (Please **specify** where to install it ?) 
I also have `resume.json` file, **Now what to do?**  
I have tried 
`resume export resume.html`
`resume export resume.pdf`
`resume test`
And got following issue, **PLEASE GUIDE ME.**

> [root@localhost jsonresume-theme-stackoverflow2]# resume export resume.html

>   running validation tests on resume.json ... 

> /usr/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:311
                    throw new Error('Not a JSON data at: ' + url + ', ' + e);
                    ^

> Error: Not a JSON data at: http://json-schema.org/draft-04/schema, SyntaxError: Unexpected token < in JSON at position 0
    at returnSchemaFromString (/usr/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:311:27)
    at Request._callback (/usr/lib/node_modules/resume-cli/node_modules/z-schema/src/ZSchema.js:339:17)
    at Request.self.callback (/usr/lib/node_modules/resume-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/resume-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/resume-cli/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Thank You.

**Comment by ShantaramTupe** [comment]
ok I found solution
I run command  `resume serve`
visited **http://localhost:4000/**, and then **Cntrl+p**, to print and **save as pdf**

Note: to continue while saving as pdf with **background images and graphics** modify `@media print{}`  from **style.css** located at where you downloaded theme.
