### ISSUE TITLE
New install init error

### ISSUE THREAD

**Issue by kolonuk** [jsonresume/resume-cli#302]
Just installed npm, then ran `npm install -g resume-cli` and did an init, and got this error:

```
/usr/lib/node_modules/resume-cli/lib/export-resume/index.js:90
  (async () => {
         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/resume-cli/lib/index.js:6:19)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
```

Have I missed anything, or is this a real bug?

**Comment by dylanwilbur** [comment]
I experienced the same error, not sure what the issue is.

**Comment by dylanwilbur** [comment]
Turns out that I was running node version 6.9.2 which seemed to have been causing the error. I used nvm to switch to node 8.7.0 which fixed the issue.

**Comment by kolonuk** [comment]
I wasn't getting the install error, but had node 6 something.  Upgraded to node 10.15.3, which seems the latest stable for me, and init now works, trying the other functions now.

Would be nice to have minimum versions in the docs...

**Comment by Alethebat** [comment]
Npm i  -- save chalk
inquirer

**Comment by Alethebat** [comment]
#!/usr/bin/env node
 "use strict":

  var inquirer = requ
  var chalk = require

**Comment by Alethebat** [comment]
Node index.js
x>

**Comment by Alethebat** [comment]
Npm   adduser

x>

**Comment by Alethebat** [comment]
###|@alethebat
"bin". {
"<npm init>" "./index.js"
}

**Comment by Alethebat** [comment]
Npm publish  --
access-public

**Comment by thomasdavis** [comment]
Will update the docs for people to use `10.x`, thanks.
