### ISSUE TITLE
resume init error

### ISSUE THREAD

**Issue by PTRFRLL** [jsonresume/resume-cli#323]
Running `resume init` produces an error no matter what I type in:

```
PS C:\Users\pfiorella\Documents\Code\node\resume> resume init

This utility will generate a resume.json file in your current working directory.
Fill out your name and email to get started, or leave the fields blank.
All fields are optional.

Press ^C at any time to quit.
name: Peter
email:
readline.js:1088
            throw err;
            ^

TypeError: Cannot read property 'basics' of undefined
    at C:\Users\pfiorella\AppData\Roaming\npm\node_modules\resume-cli\lib\init.js:28:24
    at Interface.onLine (C:\Users\pfiorella\AppData\Roaming\npm\node_modules\resume-cli\node_modules\read\lib\read.js:111:5)
    at Interface.emit (events.js:198:13)
    at Interface._onLine (readline.js:308:10)
    at Interface._line (readline.js:656:8)
    at Interface._ttyWrite (readline.js:937:14)
    at ReadStream.onkeypress (readline.js:184:10)
    at ReadStream.emit (events.js:198:13)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
```

I'm running version 1.1.2 of resume-cli on Windows 10 with Node v10.16.0.

**Comment by Crooks5001** [comment]
I am also seeing this bug, only difference is I'm consistently seeing "readline.js:1158"  rather than the above.
`readline.js:1088
            throw err;
            ^`

**Comment by JonRojas** [comment]
Same error as PTRFRLL.

resume-cli: 1.1.2
Node: v10.16.0
MacOS Mojave 10.14.5

**Comment by scitronboy** [comment]
Same issue here.

**Comment by haxtedy** [comment]
same issue on win10

**Comment by thomasdavis** [comment]
Should work in latest npm package. Thanks to @AbhishekBiswal

**Comment by haxtedy** [comment]
Thank you very much! @AbhishekBiswal

**Comment by ndgnuh** [comment]
No it's not.
```
readline.js:1021
            throw err;
            ^

TypeError: Cannot read property 'basics' of undefined
    at /usr/lib/node_modules/resume-cli/lib/init.js:28:24
    at Interface.onLine (/usr/lib/node_modules/resume-cli/node_modules/read/lib/read.js:111:5)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._line (readline.js:631:8)
    at Interface._ttyWrite (readline.js:911:14)
    at ReadStream.onkeypress (readline.js:160:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
```

**Comment by AbhishekBiswal** [comment]
@ndgnuh Hey, it worked for me. Can you check if you're using the latest version?

**Comment by ndgnuh** [comment]
Actually, I can't install the latest version because of some dependencies issue:
```log
~/ > yarn global add resume-cli
yarn global v1.21.1
[1/4] Resolving packages...
warning resume-cli > jsonlint > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning resume-cli > superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
[2/4] Fetching packages...
info fsevents@2.1.1: The platform "linux" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
error html-to-text@0.0.8: The engine "node" is incompatible with this module. Expected version "~0.8.0". Got "12.14.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```
