### ISSUE TITLE
resume "test" fails on known schema

### ISSUE THREAD

**Issue by dustinlennon** [jsonresume/resume-cli#326]
I'm working on a clone of master (7cfbd68) from Jul 9, 2019; node version is v10.16.0.  The resume.json file is copied from https://jsonresume.org/schema.

```raw
$ node index.js test

  running validation tests on resume.json ... 

Cannot export. There are errors in your resume.json schema format.

/home/dnlennon/Workspace/Repo/jsonresume/resume-cli/lib/test.js:40
    errors.errors.forEach(function(error) {
                  ^

TypeError: Cannot read property 'forEach' of undefined
    at errorFormatter (/home/dnlennon/Workspace/Repo/jsonresume/resume-cli/lib/test.js:40:19)
    at /home/dnlennon/Workspace/Repo/jsonresume/resume-cli/lib/test.js:64:13
    at callbackWrapper (/home/dnlennon/Workspace/Repo/jsonresume/resume-cli/node_modules/resume-schema/validator.js:17:7)
    at /home/dnlennon/Workspace/Repo/jsonresume/resume-cli/node_modules/z-schema/src/Report.js:46:13
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

On inspection, it looks like the arguments to one of the callback functions may have been reversed, i.e., in lib/test.js, should:

```js
resumeSchema.validate(resumeData, function(report, errs) { 
...
}
```
be 

```js
resumeSchema.validate(resumeData, function(errs, report) { 
...
}
```

**Comment by bh-adrienne** [comment]
There are 2 prs on #331 that have fixed this as well. May wish to close the issue once main CLI version is bumped.
