### ISSUE TITLE
Export html or pdf to subfolder yields error (1.2.7)

### ISSUE THREAD

**Issue by martymcflywa** [jsonresume/resume-cli#338]
# To reproduce html error
Export as html, where a subfolder is specified:
```
resume export target/index.html
```
## Html error
```
  running validation tests on resume.json ...

  ✓ Passed all validation tests.

events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/root/resume/target/index.html'
Emitted 'error' event at:
    at internal/fs/streams.js:289:12
    at FSReqCallback.oncomplete (fs.js:153:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/resume/target/index.html'
}
```
# To reproduce pdf error
Export as pdf, where a subfolder is specified:
```
resume export target/index.pdf
```

## Pdf error
```
  running validation tests on resume.json ...

  ✓ Passed all validation tests.

Error: ENOENT: no such file or directory, open 'target/index.pdf'
  -- ASYNC --
    at Page.<anonymous> (/root/resume/node_modules/puppeteer/lib/helper.js:111:15)
    at /root/resume/node_modules/resume-cli/lib/export-resume/index.js:107:16
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'target/index.pdf'
} `createPdf` errored out

Done! Find your new .pdf resume at:
 /root/resume/target/index.pdf
```
The console then hangs.

**Comment by martymcflywa** [comment]
Works if the subfolder exists in the first place! No issue.
