### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by felipecrs** [jsonresume/resume-cli#401]
I'm trying to `resume serve` my resume, but it fails.

```sh-session
$ resume serve


Preview: http://localhost:4000
Press ctrl-c to stop

TypeError: Cannot read property 'join' of undefined
    at Object.<anonymous> (C:\Users\felip\Repos\resume\node_modules\jsonresume-theme-even\index.js:26:7)
    at Object.wrapper (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:16:98)
    at prog (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
    at execIteration (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:51:19)
    at Object.<anonymous> (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\helpers\each.js:61:13)
    at Object.wrapper (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\internal\wrapHelper.js:15:19)
    at eval (eval at createFunctionContext (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:262:23), <anonymous>:9:49)
    at Object.prog [as fn] (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\runtime.js:268:12)
    at Object.<anonymous> (C:\Users\felip\Repos\resume\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:29:22)
```

I have no idea what's happening. Any help?

https://github.com/felipecrs/resume/blob/master/resume.json

**Comment by felipecrs** [comment]
This was because `roles` were missing in `projects`. This should be placed as mandatory in the schema, or at least a clear error message would be better.

**Comment by thomasdavis** [comment]
Was about to suggest that a field was missing. It is a error in the theme itself, you would need to report the issue there.

**Comment by felipecrs** [comment]
Ok, thanks!
