### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by kbrajwani** [jsonresume/resume-cli#518]
i have saved resume.json at current working directory and i am running following command.
resume export resume.pdf

Error: theme path jsonresume-theme-even could not be resolved from current working directory
    at _default (C:\Users\Kumar Rajwani\AppData\Roaming\npm\node_modules\resume-cli\build\render-html.js:43:11)
    at C:\Users\Kumar Rajwani\AppData\Roaming\npm\node_modules\resume-cli\build\export-resume.js:107:48
    at createPdf (C:\Users\Kumar Rajwani\AppData\Roaming\npm\node_modules\resume-cli\build\export-resume.js:131:5)
    at module.exports (C:\Users\Kumar Rajwani\AppData\Roaming\npm\node_modules\resume-cli\build\export-resume.js:44:5)
    at Command.<anonymous> (C:\Users\Kumar Rajwani\AppData\Roaming\npm\node_modules\resume-cli\build\main.js:67:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async C:\Users\Kumar Rajwani\AppData\Roaming\npm\node_modules\resume-cli\build\main.js:79:3 `createPdf` errored out

**Comment by anthonyjchriste** [comment]
Hi @kbrajwani were you able to get this fixed? I'm running into the same issue.

**Comment by kbrajwani** [comment]
Hey we have to install themes from npm to use it. see here https://www.npmjs.com/package/jsonresume-theme-even.
