### ISSUE TITLE
Crash when using "relative path theme"

### ISSUE THREAD

**Issue by murrple-1** [jsonresume/resume-cli#534]
Running a command like `resume export --theme "../jsonresume-theme-mytheme" --resume="./resume.json" .tmp/resume.pdf` does not work. The docs seem to suggest this invocation is valid.

Assuming that is a valid use-case, the current code at [render-html.js line 13](https://github.com/jsonresume/resume-cli/blob/a13e63bb5ec3d2a67a4f27a886268ca602051a9a/lib/render-html.js#L13) will not work, because `path` is undefined. This error is thrown in v3.0.4:

```
>> TypeError: Cannot read property 'join' of undefined
>>     at _default (/usr/lib/node_modules/resume-cli/build/render-html.js:24:28)
>>     at /usr/lib/node_modules/resume-cli/build/export-resume.js:107:48
>>     at createPdf (/usr/lib/node_modules/resume-cli/build/export-resume.js:131:5)
>>     at module.exports (/usr/lib/node_modules/resume-cli/build/export-resume.js:44:5)
>>     at Command.<anonymous> (/usr/lib/node_modules/resume-cli/build/main.js:67:5)
>>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>>     at async Promise.all (index 0)
>>     at async /usr/lib/node_modules/resume-cli/build/main.js:79:3 `createPdf` errored out
```

**Comment by murrple-1** [comment]
Duplicate of #493
