### ISSUE TITLE
Failed to launch the browser process!

### ISSUE THREAD

**Issue by jodobear** [jsonresume/resume-cli#564]
Cannot export resume and after all the errors, it still displays `Done! Find your new .pdf resume at:`

OS: Debian 10
npm: 7.10.0
node: 16.0.0
resume: 3.0.4

```
$ resume export a.pdf
Error: Failed to launch the browser process!
[0429/190250.431454:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x55a66a560b39 base::debug::CollectStackTrace()
#1 0x55a66a4d34c3 base::debug::StackTrace::StackTrace()
#2 0x55a66a4e3c80 logging::LogMessage::~LogMessage()
#3 0x55a668f75f5e content::ZygoteHostImpl::Init()
#4 0x55a66a47dcf8 content::ContentMainRunnerImpl::Initialize()
#5 0x55a66a47be0b content::RunContentProcess()
#6 0x55a66a47bf5c content::ContentMain()
#7 0x55a66a4cd3d2 headless::(anonymous namespace)::RunContentMain()
#8 0x55a66a4cd0bc headless::HeadlessShellMain()
#9 0x55a667acea03 ChromeMain
#10 0x7f366e30009b __libc_start_main
#11 0x55a667ace82a _start

Received signal 6
#0 0x55a66a560b39 base::debug::CollectStackTrace()
#1 0x55a66a4d34c3 base::debug::StackTrace::StackTrace()
#2 0x55a66a5606db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f36701b6730 (/usr/lib/x86_64-linux-gnu/libpthread-2.28.so+0x1272f)
#4 0x7f366e3137bb gsignal
#5 0x7f366e2fe535 abort
#6 0x55a66a55f665 base::debug::BreakDebugger()
#7 0x55a66a4e40f2 logging::LogMessage::~LogMessage()
#8 0x55a668f75f5e content::ZygoteHostImpl::Init()
#9 0x55a66a47dcf8 content::ContentMainRunnerImpl::Initialize()
#10 0x55a66a47be0b content::RunContentProcess()
#11 0x55a66a47bf5c content::ContentMain()
#12 0x55a66a4cd3d2 headless::(anonymous namespace)::RunContentMain()
#13 0x55a66a4cd0bc headless::HeadlessShellMain()
#14 0x55a667acea03 ChromeMain
#15 0x7f366e30009b __libc_start_main
#16 0x55a667ace82a _start
  r8: 0000000000000000  r9: 00007ffdee701500 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffdee702810 r13: aaaaaaaaaaaaaaaa r14: 00007ffdee702820 r15: 00007ffdee701fa0
  di: 0000000000000002  si: 00007ffdee701500  bp: 00007ffdee701750  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f366e3137bb  sp: 00007ffdee701500
  ip: 00007f366e3137bb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/jo/.nvm/versions/node/v16.0.0/lib/node_modules/resume-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/home/jo/.nvm/versions/node/v16.0.0/lib/node_modules/resume-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:377:35)
    at Interface.close (node:readline:548:8)
    at Socket.onend (node:readline:260:10)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) `createPdf` errored out

Done! Find your new .pdf resume at:
```

**Comment by mdic** [comment]
Same problem here, running Debian 10. Any suggestions?

OS: Debian 10
npm: 7.15.0
node: 15.14.0
resume: 3.0.4

```

Error: Failed to launch the browser process!
[0528/120236.411763:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x557fffeb7b39 base::debug::CollectStackTrace()
#1 0x557fffe2a4c3 base::debug::StackTrace::StackTrace()
#2 0x557fffe3ac80 logging::LogMessage::~LogMessage()
#3 0x557ffe8ccf5e content::ZygoteHostImpl::Init()
#4 0x557fffdd4cf8 content::ContentMainRunnerImpl::Initialize()
#5 0x557fffdd2e0b content::RunContentProcess()
#6 0x557fffdd2f5c content::ContentMain()
#7 0x557fffe243d2 headless::(anonymous namespace)::RunContentMain()
#8 0x557fffe240bc headless::HeadlessShellMain()
#9 0x557ffd425a03 ChromeMain
#10 0x7ff3fbd1309b __libc_start_main
#11 0x557ffd42582a _start

Received signal 6
#0 0x557fffeb7b39 base::debug::CollectStackTrace()
#1 0x557fffe2a4c3 base::debug::StackTrace::StackTrace()
#2 0x557fffeb76db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7ff3fdbc9730 (/usr/lib/x86_64-linux-gnu/libpthread-2.28.so+0x1272f)
#4 0x7ff3fbd267bb gsignal
#5 0x7ff3fbd11535 abort
#6 0x557fffeb6665 base::debug::BreakDebugger()
#7 0x557fffe3b0f2 logging::LogMessage::~LogMessage()
#8 0x557ffe8ccf5e content::ZygoteHostImpl::Init()
#9 0x557fffdd4cf8 content::ContentMainRunnerImpl::Initialize()
#10 0x557fffdd2e0b content::RunContentProcess()
#11 0x557fffdd2f5c content::ContentMain()
#12 0x557fffe243d2 headless::(anonymous namespace)::RunContentMain()
#13 0x557fffe240bc headless::HeadlessShellMain()
#14 0x557ffd425a03 ChromeMain
#15 0x7ff3fbd1309b __libc_start_main
#16 0x557ffd42582a _start
  r8: 0000000000000000  r9: 00007fff045450e0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fff045463f0 r13: aaaaaaaaaaaaaaaa r14: 00007fff04546400 r15: 00007fff04545b80
  di: 0000000000000002  si: 00007fff045450e0  bp: 00007fff04545330  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007ff3fbd267bb  sp: 00007fff045450e0
  ip: 00007ff3fbd267bb efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/resume-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/usr/lib/node_modules/resume-cli/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:381:22)
    at Interface.close (node:readline:540:8)
    at Socket.onend (node:readline:256:10)
    at Socket.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) `createPdf` errored out

Done! Find your new .pdf resume at:
 /PATH/TO/FOLDER/CV_jsonresume/test.pdf
```

**Comment by beaverden** [comment]
Have you tried using the `--no-sandbox` option as specified in the suggestion `If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.`?

I'm using `RESUME_PUPPETEER_NO_SANDBOX=1` which might help getting it started

**Comment by jeromeza** [comment]
Thanks @beaverden - that worked for me.

$ export RESUME_PUPPETEER_NO_SANDBOX=1
$ resume export resume.pdf --format pdf --theme /usr/lib/node_modules/jsonresume-theme-stackoverflow

Done! Find your new .pdf resume at:
 /home/node/resume.pdf

**Comment by thomasdavis** [comment]
@jodobear "Failed to launch the browser process" was the signature failure of the old puppeteer pin — the revival's bump to `^23` reworked Chromium provisioning, which fixed this class of error for most setups.

Status update: **JSON Resume is under active maintenance again (2026)**, and resume-cli has been revived — development now happens in the [jsonresume.org monorepo](https://github.com/jsonresume/jsonresume.org) at [`packages/cli`](https://github.com/jsonresume/jsonresume.org/tree/master/packages/cli): Node 18+ support, the install-breaking husky hook removed, puppeteer bumped to `^23`, tests green. The npm package name `resume-cli` is unchanged. Full announcement: #786 · Consolidation tracking: [jsonresume/jsonresume.org#275](https://github.com/jsonresume/jsonresume.org/issues/275).

This standalone repo is being archived with a redirect, so I'm closing this out as part of the migration triage. If this still affects you on the revived version, please open a fresh issue in the monorepo where it will actually get eyes: https://github.com/jsonresume/jsonresume.org/issues. Thanks for taking the time to report it — and sorry it sat unanswered for so long.
