### ISSUE TITLE
theme path jsonresume-theme-even could not be resolved from current working directory

### ISSUE THREAD

**Issue by adewinter** [jsonresume/resume-cli#626]
When I follow the "Getting Started" instructions on [the homepage](https://jsonresume.org/getting-started/) the following error occurs:
```
PS C:\Users\adewi\Desktop> resume export resume.pdf
Error: theme path jsonresume-theme-even could not be resolved from current working directory
    at _default (C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\render-html.js:46:11)
    at C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\export-resume.js:107:48
    at createPdf (C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\export-resume.js:131:5)
    at module.exports (C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\export-resume.js:44:5)
    at Command.<anonymous> (C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\main.js:67:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\main.js:79:3 `createPdf` errored out

Done! Find your new .pdf resume at:
 C:\Users\adewi\Desktop\resume.pdf
 ```
 
 Despite claiming that a PDF has been generated in the last two lines, this is not the case.  I'm not sure how to go about fixing the problem.  There does not seem to be any documentation on jsonresume.org that indicates how themes work or how to use them for exporting a PDF. 
 
 Any advice on how to fix this issue would be appreciated!
 
 Thanks,
Anton

# Steps to recreate:
**Platform: Windows 10/Powershell**
Commands:
* npm install -g resume-cli
* ensure "resume.json" is valid and located in the cwd
* run `resume export resume.pdf`

**Expected results:**
A PDF of my resume in the default theme

**Actual results:**
Error message:
```
PS C:\Users\adewi\Desktop> resume export resume.pdf
Error: theme path jsonresume-theme-even could not be resolved from current working directory
    at _default (C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\render-html.js:46:11)
    at C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\export-resume.js:107:48
    at createPdf (C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\export-resume.js:131:5)
    at module.exports (C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\export-resume.js:44:5)
    at Command.<anonymous> (C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\main.js:67:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async C:\Users\adewi\AppData\Roaming\nvm\v16.4.2\node_modules\resume-cli\build\main.js:79:3 `createPdf` errored out

Done! Find your new .pdf resume at:
 C:\Users\adewi\Desktop\resume.pdf
```

**Comment by brandonxoliver** [comment]
I have the same problem. I'm excited to use this tool and really hope there's a fix on the horizon!

**Comment by alsaedwy** [comment]
Same issue!

**Comment by aedifex** [comment]
Also encountering the issue on macOS 11.4. I've been poking around the codebase some...hoping for a straightforward fix! I'll throw up a PR if I can make some progress.

**Comment by SethFalco** [comment]
Just tested, seems this occurs when using `resume-cli` installed globally. (ie `npm i -g resume-cli`)
It appears to work as intended when using `resume-cli` installed in the current project/directory. (ie `npm i resume-cli`)

Not ideal, but is a valid workaround for now.

**Comment by aedifex** [comment]
@SethFalco this is admittedly a silly question but how do you get the CLI to run when you've installed it locally?

**Comment by SethFalco** [comment]
@aedifex Not a silly question at all.

When you install `resume-cli` locally to the directory, you'll get a new directory called `node_modules/.bin`, which contains tools your dependencies came with. You can use `npm`/`npx` to execute them.

You could add the command to your `scripts` array in `package.json`.
`npm run` will execute binaries in the `node_modules/.bin` directory in your project/directory.

```json
{
  "scripts": {
    "build:pdf": "resume export resume.pdf"
  },
  "devDependencies": {
    "resume-cli": "^3.0.5"
  }
}
```

```sh
npm run build:pdf
```

Alternatively, you can just use `npx` (npm package executor), which is bundled with NPM.
NPX lets you execute binaries in your `node_modules/.bin` directory in your project/directory.

```sh
npx resume export resume.pdf
```

**Comment by aedifex** [comment]
Thank you much @SethFalco, appreciate the thoughtful explanation.

**Comment by dsaw** [comment]
same issue for me..would prefer a use case where a new javascript repository is not needed.

**Comment by rnzfan** [comment]
Thank you, @SethFalco it works!

**Comment by RomanRcT** [comment]
> npx resume export r.pdf
Error: theme path jsonresume-theme-even could not be resolved from current working directory
    at _default (/usr/local/lib/node_modules/resume-cli/build/render-html.js:46:11)
    at /usr/local/lib/node_modules/resume-cli/build/export-resume.js:107:48
    at createPdf (/usr/local/lib/node_modules/resume-cli/build/export-resume.js:131:5)
    at module.exports (/usr/local/lib/node_modules/resume-cli/build/export-resume.js:44:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/build/main.js:67:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async /usr/local/lib/node_modules/resume-cli/build/main.js:79:3 `createPdf` errored out

Done! Find your new .pdf resume at:
 /home/roman/cv/r.pdf
 

This is doesn't work for me.

**Comment by dantiston** [comment]
@adewinter why is this issue closed? As of January 2023 (1.5 years after this issue was initially posted), the website's "Getting Started" page still has instructions to use:

> npm install -g resume-cli
> resume export resume.html

But this error still occurs. If this is expected behavior, maybe the website should be changed? Or if it's not expected behavior, this bug can be fixed?

**Comment by SethFalco** [comment]
> why is this issue closed?

It was closed because the author of this issue opted to close it. :shrug: 

Meanwhile, I do agree this issue shouldn't be considered resolved. I'll reopen it for now and assign it to myself.

**Comment by dantiston** [comment]
Thanks, @SethFalco!

**Comment by thomasdavis** [comment]
@adewinter theme-path resolution has been the CLI's most reported rough edge — it's actively on the radar in the revival (see #784, which we're keeping open to track exactly this family of problems).

Status update: **JSON Resume is under active maintenance again (2026)**, and resume-cli has been revived — development now happens in the [jsonresume.org monorepo](https://github.com/jsonresume/jsonresume.org) at [`packages/cli`](https://github.com/jsonresume/jsonresume.org/tree/master/packages/cli): Node 18+ support, the install-breaking husky hook removed, puppeteer bumped to `^23`, tests green. The npm package name `resume-cli` is unchanged. Full announcement: #786 · Consolidation tracking: [jsonresume/jsonresume.org#275](https://github.com/jsonresume/jsonresume.org/issues/275).

This standalone repo is being archived with a redirect, so I'm closing this out as part of the migration triage. If this still affects you on the revived version, please open a fresh issue in the monorepo where it will actually get eyes: https://github.com/jsonresume/jsonresume.org/issues. Thanks for taking the time to report it — and sorry it sat unanswered for so long.
