### ISSUE TITLE
Error: net::ERR_ABORTED when converting to PDF with custom theme

### ISSUE THREAD

**Issue by asbjornu** [jsonresume/resume-cli#763]
When executing the following:

```sh
resume export --theme . --resume ../asbjor.nu/resume.json --format pdf ./asbjornu.pdf
```

I get the error:

```ts
Error: net::ERR_ABORTED at data:text/html;base64,PC…Pgo=
    at navigate (/Users/bitbear/Dev/jsonresume-theme-kards/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:199:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Frame.goto (/Users/bitbear/Dev/jsonresume-theme-kards/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:169:21)
    at async Page.goto (/Users/bitbear/Dev/jsonresume-theme-kards/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1144:16)
    at async /Users/bitbear/Dev/jsonresume-theme-kards/node_modules/resume-cli/build/export-resume.js:118:5 `createPdf` errored out
```

Interestingly, JSON Resume concludes that despite of Puppeteer crashing, everything went fine and halts infinitely after printing this:

```
Done! Find your new .pdf resume at:
  ~/Dev/jsonresume-theme-kards/asbjornu.pdf
```

Thoughts?

**Comment by asbjornu** [comment]
I'm not sure, but https://github.com/puppeteer/puppeteer/issues/2794 may be relevant.

**Comment by thomasdavis** [comment]
@asbjornu the `net::ERR_ABORTED` during PDF export traces back to the old puppeteer version's request handling — the revival bumped puppeteer to `^23`, which reworked that area. Worth a retest with your custom theme.

Status update: **JSON Resume is under active maintenance again (2026)**, and resume-cli has been revived — development now happens in the [jsonresume.org monorepo](https://github.com/jsonresume/jsonresume.org) at [`packages/cli`](https://github.com/jsonresume/jsonresume.org/tree/master/packages/cli): Node 18+ support, the install-breaking husky hook removed, puppeteer bumped to `^23`, tests green. The npm package name `resume-cli` is unchanged. Full announcement: #786 · Consolidation tracking: [jsonresume/jsonresume.org#275](https://github.com/jsonresume/jsonresume.org/issues/275).

This standalone repo is being archived with a redirect, so I'm closing this out as part of the migration triage. If this still affects you on the revived version, please open a fresh issue in the monorepo where it will actually get eyes: https://github.com/jsonresume/jsonresume.org/issues. Thanks for taking the time to report it — and sorry it sat unanswered for so long.
