### ISSUE TITLE
cli is broken

### ISSUE THREAD

**Issue by adius** [jsonresume/resume-cli#95]
```
adius:~$ resume

module.js:340
    throw err;
          ^
Error: Cannot find module 'node-static'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/lib/serve.js:4:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/resume-cli/lib/index.js:8:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by thomasdavis** [comment]
Thanks! Just merged a PR recently which had placed the dependency in the wrong section of package.json. I've fixed it and bumped the NPM version.

It should work if you reinstall via npm
